### ISSUE TITLE
Documentation reactiveLayer

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-hri#37]
Cleanup is done (#16), documentation remains to be written.

**Comment by Tobias-Fischer** [comment]
Reminder to myself: The tutorial on proactive tagging needs updating, it contains wrong references to followingOrder.

**Comment by Tobias-Fischer** [comment]
Fixed the tutorial in https://github.com/robotology/icub-client/commit/d18558d9b35dcb922523887af7c8a286c96b88e1 - the rest is up to you @jypuigbo @clement-moulin-frier

**Comment by Tobias-Fischer** [comment]
Hi @jypuigbo,
The documentation looks good now, I'm just doing some more cleanup.
A quick question. In `sensationManager`, it seems like `kp_entities` and `k_entities` are not used. Can they be removed? Also, for the other items, it seems like they are just infinitely expanded every time as there is no `u_entities.clear()` etc. anywhere. Should they be local variables within `handleEntities()` instead?
Thanks, Tobi

**Comment by Tobias-Fischer** [comment]
We can close this issue once the above is resolved :+1:

**Comment by jypuigbo** [comment]
I'm checking that right now.

**Comment by jypuigbo** [comment]
I see what you mean. As you prefer. I can just remove every instance of `*_entities` except the ones used, as they were used for WYSIWYD but not necessarily here. Now they might just be noisy for understanding the code. 
Also, I would make them local (as they were originally). If you give me a go signal, I change it now. 

J.

**Comment by Tobias-Fischer** [comment]
@jypuigbo Yes please, go ahead and change. Thanks a lot :)

**Comment by jypuigbo** [comment]
Sorry, I didn't realize they were used in `get_property`. I just cleared the bottles at the start of `handleEntities` is called, then. 

Let me know if anything else is needed.

**Comment by Tobias-Fischer** [comment]
All good, thanks a lot!
