### ISSUE TITLE
iCub.getPartnerName not finding partner

### ISSUE THREAD

**Issue by dcam0050** [robotology/icub-hri#43]
Hey everyone I'm having an issue with getPartnerName and consequently with lookAtPartner. Whenever I try and run the following code I get `[WARNING]No partner present was found!`

I've tracked it down to `icub-client/src/libraries/icubclient/src/clients` line 251 ```list<shared_ptr<Entity>> lEntities = opc->EntitiesCacheCopy();```

The returned list only has one item in it which is icub whereas both icub and partner are present in the `OPC` when I query `OPC` via `/OPC/rpc`.

I've added a picture here of the modules I'm running in case I'm missing one

![yarpmanager](https://user-images.githubusercontent.com/4288535/31505898-d5cfb706-af6d-11e7-9870-e491863a9d3c.png)

And this is the example code I'm trying

```#!/usr/bin/env python
import yarp
import icubclient
import sys 

yarp.Network.init()
iCub = icubclient.ICubClient("Demo")

rfClient = yarp.ResourceFinder()
rfClient.setVerbose(True)
rfClient.setDefaultContext("icubClient")
rfClient.setDefaultConfigFile("client.ini")
rfClient.configure(sys.argv)

if not iCub.connect():
    print "not connected"
d = iCub.getPartnerName(verbose=True)
print d

iCub.lookAtPartner()
iCub.say("Hello demoing here")
iCub.home("all")
iCub.lookAtPartner()
iCub.say("bye bye")
iCub.home("all")

iCub.close()
yarp.Network.fini()```

**Comment by Tobias-Fischer** [comment]
Hey, try whether a `iCub.opc.checkout()` before the `iCub.lookAtPartner()` helps.

Best, Tobi

**Comment by dcam0050** [comment]
Thanks Tobi! Worked like a charm
